### PR TITLE
Issue@110

### PR DESCRIPTION
**Pull request by Samuroldan**
Issue#110 DONE

### CODE REVIEW

**Review by hectorAlarcon — APPROVED** [review]
Very well done! everything works is prepared for the upcoming.
It would be nice if you could comment your code, at least what the components are supposed to do and how it can be used.

**Comment by AlbertCaTa** [comment]
Everything looking great! There are a few things left to do:
- For each component comment what the component issupposed to do and how it can be used.
- Refactor Home.js so that it only uses the components you described, right now it is a mix of the old way of showing the lists and the new way of showing the lists with the components. Every list that appears in the page should be a component. Home.js shouldn't have more than 100 lines of code.

**Review by AlbertCaTa — CHANGES_REQUESTED** [review]
Everything looking great! There are a few things left to do:
- For each component comment what the component issupposed to do and how it can be used.
- Refactor Home.js so that it only uses the components you described, right now it is a mix of the old way of showing the lists and the new way of showing the lists with the components. Every list that appears in the page should be a component. Home.js shouldn't have more than 100 lines of code.

Comment: should RestPreviewGeneral.js show the price range of each restaurant?

**Comment by AlbertCaTa** [comment]
Spot on!

**Review by AlbertCaTa — CHANGES_REQUESTED** [review]
Spot on!

**Review by AlbertCaTa — APPROVED** [review]
Spot on! Thanks for the changes!

**Pull request merged**
