### PR TITLE
#154

### PR DESCRIPTION
**Pull request by Samuroldan**
DONE

### CODE REVIEW

**Review by aldakata — COMMENTED** [review]
Samu, explicame de que va este pull request, no solo pongas DONE que no me entero de que tengo que hacer review.

Me he leido el issue154 y es el del shopping cart, donde puedo acceder a ello? En el homepage no me aparece ningun preview de restaurante ni nigun boton de shopping cart.

**Comment by Samuroldan** [comment]
Esto ha sido fallomio que por algunmotivo no se ha subido la modificacion, esto lo arreglomañana en un momento. Sorry.

**Comment by Samuroldan** [comment]
Los restaurantes no s emuestran por el error que ya comentamos, pero no son necesarios para este caso. Puedes ver como queda en componente en /shopping aunque he decidido no añadir unboton ni una pagina porque al no tener funcionalidad creo que es mejor no utilizarlo.

**Review by aldakata — APPROVED** [review]
The code looks good.
The layout is up to @hectorAlarcon 
It's an approve for me!

**Review by hectorAlarcon — CHANGES_REQUESTED** [review]
The code submitted is okay but doesn't match the AC stated at #154, in fact the only AC that can be checked would be the last one. 
The issue cant be marked as DONE, I understand as this is not going to be included in the final product as a new functionality but I can't approve it. 
To sum up, the shopping cart must be a component and can be reached from every page from navbar. Also it shouldn't be a separate page, as I mentioned before it can be reached anywhere as a 'component', working similarly to a Sidebar.

**Comment by Samuroldan** [comment]
Button working. I won't be able to create this as a separate component. I will let be a different page like amazon or similar pages.

**Review by hectorAlarcon — CHANGES_REQUESTED** [review]
It works well and I'll accept the part where the shopping cart reamins in a different page as long as the data displayed is aligned ( this last part was not reviewed before and should have been, my bad). To align use [Row](https://react-bootstrap.github.io/layout/grid/) as explained here. In fact you can embed everything in a <Row> </Row> element and should work fine.

Also it would help a lot if the data shown is prepared to be dynamic, in other words to have an Array of products with price,title and quantity, then iterate this array to display each product.  You can see an example in ProfileRestaurant

**Review by hectorAlarcon — APPROVED** [review]
Works fine! Good job

**Pull request merged**
