### PR TITLE
Iss147:   {4 hrs}[US-9] API search queries

### PR DESCRIPTION
**Pull request by oriolOrnaque**
- [x] GET endpoint with the query as parameter
- [x] Search by name substring
- [x] Tests for the endpoint
- [x] Update documentation with the new endpoint

### CODE REVIEW

**Review by hectorAlarcon — COMMENTED** [review]
Overall good work but as I'd like to comment on something it ocurred to me: 

1. The query response contains only email and name. Should the response be more similar to GET all restaurant endpoint ? (Decision with Front)

If @aldakata checks it and validates it its okay to me. Good job!

**Review by aldakata — APPROVED** [review]
Reviewed, good work.

**Comment by oriolOrnaque** [comment]
@hectorAlarcon  @aldakata requested changes done and tested. Docs updated too. Enjoyéalo

**Review by aldakata — APPROVED** [review]
Thanks for the changes, waiting 4 merge  😄

**Pull request merged**
